
# Modules build makefile
COMPILE_ROOT := $(shell pwd)
PDT_ROOT     ?= $(COMPILE_ROOT)/..
include $(PDT_ROOT)/build/base.mak

# Sub-Modules List
SUBDIRS := speedtest

# Sub-Modules Compile
include $(PDT_ROOT)/build/script/subdir.mak



